parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2020
  sourceType: module

env:
  browser: true
  es6: true
  node: true

plugins:
  - import

extends:
  - eslint:recommended
  - plugin:prettier/recommended
