[package]
name = "libdenolint"
version = "2.0.9"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_lint = "0.45.0"
global_alloc = { path = "../../crates/alloc" }
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.7", default-features = false, features = ["napi4"] }
napi-derive = "2.12.5"
shared = { path = "../../crates/shared" }

[build-dependencies]
napi-build = "2.0.1"
