[package]
name = "denolint"
version = "2.0.4"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
atty = "0.2.14"
deno_ast = "0.21.0"
deno_lint = { version = "0.35.0", features = ["docs"] }
global_alloc = { path = "../../crates/alloc" }
if_chain = "1.0.2"
pulldown-cmark = "0.9.2"
serde = "1.0.147"
serde_json = "1.0.87"
shared = { path = "../../crates/shared" }
