[package]
name = "denolint"
version = "2.0.5"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
atty = "0.2.14"
deno_ast = "0.23.2"
deno_lint = { version = "0.37.0", features = ["docs"] }
global_alloc = { path = "../../crates/alloc" }
if_chain = "1.0.2"
pulldown-cmark = "0.9.2"
serde = "1.0.152"
serde_json = "1.0.91"
shared = { path = "../../crates/shared" }
